---
- name: Initialise DNS recode variables at Domain
  ansible.builtin.set_fact:
    dns_domain: "{{ gather_dns_domain.key }}"
    dns_domain_setting: "{{ gather_dns_domain.value | default({}, true) }}"
    dns_domain_recodes: {}
- name: SPF recode value
  ansible.builtin.import_tasks:
    file: recode/SPF.yml
  when: not (dns_domain_setting.spf_skip | default(false))
- name: DKIM recode value
  ansible.builtin.import_tasks:
    file: recode/DKIM.yml
- name: DMARC recode value
  ansible.builtin.import_tasks:
    file: recode/DMARC.yml
  when: dns_domain == dns_domain | community.dns.get_registrable_domain
- name: Combine DNS recode variable
  ansible.builtin.set_fact:
    dns_recodes: "{{ dns_recodes | combine({dns_domain: dns_domain_recodes}, recursive=true) }}"
