---
- name: Initialice DNS recode variables at Domain
  ansible.builtin.set_fact:
    dns_domain_recodes: {}
- name: SPF recode value
  ansible.builtin.import_tasks:
    file: recode/SPF.yml
- name: DKIM recode value
  ansible.builtin.import_tasks:
    file: recode/DKIM.yml
- name: DMARC recode value
  ansible.builtin.import_tasks:
    file: recode/DMARC.yml
- name: Combine DNS recode variable
  ansible.builtin.set_fact:
    dns_recodes: "{{ dns_recodes | combine({dns_domain: dns_domain_recodes}, recursive=true) }}"
