---
- name: Initialise DNS recode variables at Domain
  ansible.builtin.set_fact:
    dns_domain: "{{ gather_dns_domain.key }}"
    dns_domain_setting: "{{ gather_dns_domain.value | default({}, true) }}"
    dns_domain_recodes: {}
- name: A recode value
  ansible.builtin.import_tasks:
    file: recode/A.yml
  when:
    - not dns_domain_setting.skip_a | default(false)
    - (dns_domain_setting.ipaddr.ipv4 is defined or ansible_facts.default_ipv4.address is defined)
- name: AAAA recode value
  ansible.builtin.import_tasks:
    file: recode/AAAA.yml
  when:
    - not dns_domain_setting.skip_aaaa | default(false)
    - (dns_domain_setting.ipaddr.ipv6 is defined or ansible_facts.default_ipv6.address is defined)
- name: SPF recode value
  ansible.builtin.import_tasks:
    file: recode/SPF.yml
  when:
    - not (dns_domain_setting.skip_spf | default(false))
- name: DKIM recode value
  ansible.builtin.import_tasks:
    file: recode/DKIM.yml
  when:
    - not (dns_domain_setting.skip_dkim | default(false))
- name: DMARC recode value
  ansible.builtin.import_tasks:
    file: recode/DMARC.yml
  when:
    - dns_domain == dns_domain | community.dns.get_registrable_domain
    - not (dns_domain_setting.skip_dmarc | default(false))
- name: Google site verification recode value
  ansible.builtin.import_tasks:
    file: recode/site_verification.yml
  when:
    - dns_domain_setting.site_verification is defined
    - not (dns_domain_setting.skip_site_verification | default(false))
- name: CNAME recode value
  ansible.builtin.import_tasks:
    file: recode/CNAME.yml
  when:
    - dns_domain_setting.cname is defined
- name: CAA recode value
  ansible.builtin.import_tasks:
    file: recode/CAA.yml
  when:
    - not (dns_domain_setting.skip_caa | default(false))
    - (dns_domain_setting.caa is defined or dns_caa_default.ca_domain is defined)
- name: Combine DNS recode at {{ dns_domain }}
  ansible.builtin.set_fact:
    dns_recodes: "{{ dns_recodes | combine({dns_domain: dns_domain_recodes}, recursive=true) }}"
- name: Output CSV report file
  when: dns_recode_output_dir | length > 0
  become: false
  delegate_to: 127.0.0.1
  block:
    - name: Output CSV report file
      ansible.builtin.template:
        src: report.csv.j2
        dest: "{{ dns_recode_output_dir.endswith('/') | ternary(dns_recode_output_dir, dns_recode_output_dir + '/') }}{{ dns_domain }}.csv"
        mode: "0644"
    - name: Output Markdown report file
      ansible.builtin.template:
        src: report.md.j2
        dest: "{{ dns_recode_output_dir.endswith('/') | ternary(dns_recode_output_dir, dns_recode_output_dir + '/') }}{{ dns_domain }}.md"
        mode: "0644"
