# code: language=ansible
---
- name: Import dependency task
  ansible.builtin.import_tasks:
    file: dependency.yml
  tags:
    - role_dns_dependency
- name: Gather IP Address
  ansible.builtin.setup:
    gather_subset:
      - default_ipv4
      - default_ipv6
- name: Pickup registrable domain
  ansible.builtin.set_fact:
    tmp_domains: "{{ (tmp_domains | default([])) + [(tmp_dns_domain.key | community.dns.get_registrable_domain)] }}"
  loop: "{{ dns_domains | dict2items }}"
  loop_control:
    loop_var: tmp_dns_domain
- name: Add get_registrable domain to dns_domains variable
  ansible.builtin.set_fact:
    dns_domains: "{{ dns_domains | combine({tmp_domain: {'spf_skip': true}}) }}"
  when: dns_domains[tmp_domain] is undefined
  loop: "{{ tmp_domains | unique }}"
  loop_control:
    loop_var: tmp_domain
- name: Initialise dkim key table
  ansible.builtin.set_fact:
    dns_dkim_key_table_data: {}
- name: Check opendkim role variable
  when:
    - opendkim_selector is defined
    - opendkim_table_config_dir is defined
  block:
    - name: Set dns_dkim_key_table variable task
      ansible.builtin.import_tasks:
        file: parse_dkim_key_table.yml
- name: 各ドメイン毎のDNS設定情報を取得
  ansible.builtin.include_tasks:
    file: gather_dns_recode.yml
  loop: "{{ dns_domains | dict2items }}"
  loop_control:
    loop_var: gather_dns_domain
    label: gather_dns_domain.key
- name: Display DNS recode setting info
  ansible.builtin.debug:
    var: dns_recodes
