# code: language=ansible
---
- name: Gather IP Address
  ansible.builtin.setup:
    gather_subset:
      - default_ipv4
      - default_ipv6
- name: SPF recode value
  ansible.builtin.import_tasks:
    file: recode/SPF.yml
- name: DKIM recode value
  ansible.builtin.import_tasks:
    file: recode/DKIM.yml
- name: DMARC recode value
  ansible.builtin.import_tasks:
    file: recode/DMARC.yml
- name: PTR recode value
  ansible.builtin.import_tasks:
    file: recode/PTR.yml
- name: Debug
  ansible.builtin.debug:
    var: dns_recodes
