# code: language=ansible
---
- name: Install dependency packages
  ansible.builtin.apt:
    name:
      - python3-dnspython
      - python3-publicsuffix2
- name: Gather IP Address
  ansible.builtin.setup:
    gather_subset:
      - default_ipv4
      - default_ipv6
- name: Collect DNS records
  dns_record_info:
    domains: "{{ dns_domains }}"
    server_ipv4: "{{ ansible_facts.default_ipv4.address | default(omit) }}"
    server_ipv6: "{{ ansible_facts.default_ipv6.address | default(omit) }}"
    opendkim_keytable_path: "{{ dns_opendkim_keytable_path }}"
    spf_default: "{{ dns_spf_default }}"
    dkim_default: "{{ dns_dkim_default }}"
    dmarc_default: "{{ dns_dmarc_default }}"
    caa_default: "{{ dns_caa_default }}"
    ttl_default: "{{ dns_ttl_default }}"
  register: dns_record_result
  tags: role_dns_collect
- name: Set DNS record variables
  ansible.builtin.set_fact:
    dns_records: "{{ dns_record_result.records }}"
    dns_zones: "{{ dns_record_result.zones }}"
    dns_dkim_key_table_data: "{{ dns_record_result.dkim_keytable_data }}"
    dns_dkim_key_items: "{{ dns_record_result.dkim_key_items }}"
  tags: role_dns_set_vars
- name: Output DNS reports and zone files
  when: dns_zones | length > 0
  become: false
  delegate_to: 127.0.0.1
  vars:
    dns_output_dir: "{{ dns_record_output_dir.endswith('/') | ternary(dns_record_output_dir[:-1], dns_record_output_dir) }}"
  block:
    - name: Create output dir
      ansible.builtin.file:
        path: "{{ dns_output_dir }}"
        state: directory
        mode: "0755"
    - name: Output CSV report file
      ansible.builtin.template:
        src: report.csv.j2
        dest: "{{ dns_output_dir }}/{{ dns_domain }}.csv"
        mode: "0644"
      loop: "{{ dns_records.keys() | list }}"
      loop_control:
        loop_var: dns_domain
        label: "{{ dns_domain }}.csv"
      vars:
        dns_domain_records: "{{ dns_records[dns_domain] }}"
    - name: Output Markdown report file
      ansible.builtin.template:
        src: report.md.j2
        dest: "{{ dns_output_dir }}/{{ dns_domain }}.md"
        mode: "0644"
      loop: "{{ dns_records.keys() | list }}"
      loop_control:
        loop_var: dns_domain
        label: "{{ dns_domain }}.md"
      vars:
        dns_domain_records: "{{ dns_records[dns_domain] }}"
    - name: Generate zone file
      ansible.builtin.template:
        src: zone_file.txt.j2
        dest: "{{ dns_output_dir }}/zone_{{ dns_zone }}.txt"
        mode: "0644"
      loop: "{{ dns_zones.keys() | list }}"
      loop_control:
        loop_var: dns_zone
        label: "zone_{{ dns_zone }}.txt"
      vars:
        dns_zone_data:
          key: "{{ dns_zone }}"
          value: "{{ dns_zones[dns_zone] }}"
- name: Save OpenDKIM key files
  when:
    - dns_save_opendkim_keys | bool
    - dns_dkim_key_items | length > 0
  become: false
  delegate_to: 127.0.0.1
  vars:
    dns_opendkim_keys_output_dir: "{{ dns_record_output_dir.endswith('/') | ternary(dns_record_output_dir[:-1], dns_record_output_dir) }}/{{ dns_opendkim_keys_dir }}"
  block:
    - name: Create OpenDKIM keys output directory
      ansible.builtin.file:
        path: "{{ dns_opendkim_keys_output_dir }}"
        state: directory
        mode: "0755"
    - name: Save OpenDKIM key files
      ansible.builtin.fetch:
        src: "{{ item.data.key_path }}"
        dest: "{{ dns_opendkim_keys_output_dir }}/{{ item.domain }}_{{ item.name }}{{ item.data.key_path | regex_search('\\.[^.]+$') | default('', true) }}"
        flat: true
      loop: "{{ dns_dkim_key_items }}"
      loop_control:
        label: "{{ item.domain }}/{{ item.name }}"
