---
- name: Get key table content
  ansible.builtin.command:
    cmd: cat {{ opendkim_table_config_dir }}/KeyTable
    removes: "{{ opendkim_table_config_dir }}/KeyTable"
  register: cat_key_table_result
- name: Debug
  when: cat_key_table_result.stdout_lines | default([]) | length > 0
  block:
    - name: Set tmp variables
      ansible.builtin.set_fact:
        dns_tmp_key_tables: "{{ cat_key_table_result.stdout_lines | map('split', ' ') }}"
        dns_dkim_domains: []
        dns_dkim_names: []
        dns_dkim_selectors: []
        dns_dkim_paths: []
    - name: Set dkim dns names
      ansible.builtin.set_fact:
        dns_dkim_domains: "{{ dns_dkim_domains + [dns_tmp_key_table[1].split(':')[0]] }}"
        dns_dkim_names: "{{ dns_dkim_names + [(dns_tmp_key_table[0] | community.dns.remove_registrable_domain)] }}"
        dns_dkim_paths: "{{ dns_dkim_paths + [(dns_tmp_key_table[1].split(':')[2] | replace('.private', '.txt'))] }}"
      loop: "{{ dns_tmp_key_tables }}"
      loop_control:
        loop_var: dns_tmp_key_table
    - name: Set dns_dkim_key_table variable
      ansible.builtin.set_fact:
        dns_dkim_key_table_data: "{{ dict(dns_dkim_domains | zip(dns_dkim_names | zip(dns_dkim_paths))) }}"
