---
opendkim_domains:
  - example.com
  - subdomain.example.com
  - subdomain.example.net

dns_domains:
  example.com:
    # skip_a: true
    # skip_aaaa: true
    # skip_spf: true
    # skip_dkim: true
    # skip_site_verification: true
    # skip_dmarc: false
    # skip_caa: true
    dmarc:
      sp: none
      rua: rua-report@example.com
      ruf: ruf-report@example.com
    dkim:
      ## 自動生成されたゾーンファイルが存在しない場合に設定する公開鍵の内容
      ## ※自動生成されたゾーンファイルが存在はその内容が優先される
      p: public_key_content
    cnames:
      - www
      - mail
  example.co.jp:
  subdomain.example.com:
  subdomain.example.net:
    ipaddr:
      ipv4: 123.123.123.123
      # ipv6: "[::]1"
    spf:
      all_qualifier: "?"
      other_values:
        - include:_spf.google.com
    ## @see https://postmaster.google.com/
    site_verification: google-site-verification=1234567890abcdefghijklmnopqrstuvwxyz

dns_recode_output_dir: ./output
