---
- name: Initialize zone A record variable
  ansible.builtin.set_fact:
    dns_zones: "{{ dns_zones | combine({dns_zone: {'A': []}}, recursive=true) }}"
  when: dns_zones[dns_zone]['A'] is undefined
- name: Set record value variables
  ansible.builtin.set_fact:
    dns_record_value: "{{ lookup('ansible.builtin.template', 'record/A.j2') | trim }}"
- name: Combine A record
  ansible.builtin.set_fact:
    dns_domain_records: "{{ dns_domain_records | combine({'A': dns_record}, recursive=true) }}"
  vars:
    dns_record:
      name: "{{ dns_record_name }}"
      type: A
      value: "{{ dns_record_value }}"
      ttl: "{{ dns_ttl_default }}"
- name: Append zone A record variable
  ansible.builtin.set_fact:
    dns_zones: "{{ dns_zones | combine({dns_zone: {'A': [dns_zone_data]}}, recursive=true, list_merge='append') }}"
  vars:
    dns_zone_data:
      name: "{{ (dns_record_name == '@') | ternary('', dns_record_name + '.') }}{{ dns_zone }}."
      ttl: "{{ dns_ttl_default }}"
      type: A
      value: "{{ dns_record_value }}"
