---
- name: Initialize zone AAAA record variable
  ansible.builtin.set_fact:
    dns_zones: "{{ dns_zones | combine({dns_zone: {'AAAA': []}}, recursive=true) }}"
  when: dns_zones[dns_zone]['AAAA'] is undefined
- name: Set record value variables
  ansible.builtin.set_fact:
    dns_record_value: "{{ lookup('ansible.builtin.template', 'record/AAAA.j2') | trim }}"
- name: Combine AAAA record
  ansible.builtin.set_fact:
    dns_domain_records: "{{ dns_domain_records | combine({'AAAA': dns_record}, recursive=true) }}"
  vars:
    dns_record:
      name: "{{ dns_record_name }}"
      type: AAAA
      value: "{{ dns_record_value }}"
      ttl: "{{ dns_ttl_default }}"
- name: Append zone AAAA record variable
  ansible.builtin.set_fact:
    dns_zones: "{{ dns_zones | combine({dns_zone: {'AAAA': [dns_zone_data]}}, recursive=true, list_merge='append') }}"
  vars:
    dns_zone_data:
      name: "{{ (dns_record_name == '@') | ternary('', dns_record_name + '.') }}{{ dns_zone }}."
      ttl: "{{ dns_ttl_default }}"
      type: AAAA
      value: "{{ dns_record_value }}"
