---
- name: Initialize zone CAA record variable
  ansible.builtin.set_fact:
    dns_zones: "{{ dns_zones | combine({dns_zone: {'CAA': []}}, recursive=true) }}"
  when: dns_zones[dns_zone]['CAA'] is undefined
- name: Set record value variables
  ansible.builtin.set_fact:
    dns_record_value: "{{ lookup('ansible.builtin.template', 'record/CAA.j2') | trim | replace('\n', ' ') }}"
    dns_zone_value_parts: "{{ lookup('ansible.builtin.template', 'record/CAA.j2').split('\n') }}"
- name: Combine CAA record value
  ansible.builtin.set_fact:
    dns_domain_records: "{{ dns_domain_records | combine({'CAA': dns_record}, recursive=true) }}"
  vars:
    dns_record:
      name: "{{ dns_record_name }}"
      type: CAA
      value: "{{ dns_record_value }}"
      ttl: "{{ dns_ttl_default }}"
- name: Append zone CAA record variable
  ansible.builtin.set_fact:
    dns_zones: "{{ dns_zones | combine({dns_zone: {'CAA': [dns_zone_data]}}, recursive=true, list_merge='append') }}"
  vars:
    dns_zone_data:
      name: "{{ (dns_record_name == '@') | ternary('', dns_record_name + '.') }}{{ dns_zone }}."
      ttl: "{{ dns_ttl_default }}"
      type: CAA
      value: '{{ dns_zone_value_parts[0] }} {{ dns_zone_value_parts[1] }} "{{ dns_zone_value_parts[2] }}"'
