---
- name: Initialize zone TXT record variable
  ansible.builtin.set_fact:
    dns_zones: "{{ dns_zones | combine({dns_zone: {'TXT': []}}, recursive=true) }}"
  when: dns_zones[dns_zone]['TXT'] is undefined
- name: Set record value variables
  ansible.builtin.set_fact:
    dns_record_value: "{{ lookup('ansible.builtin.template', 'record/DMARC.j2') | trim | replace('\n', '; ') }}"
- name: Combine DMARC record
  ansible.builtin.set_fact:
    dns_domain_records: "{{ dns_domain_records | combine({'DMARC': dns_record}, recursive=true) }}"
  vars:
    dns_record:
      name: _dmarc
      type: TXT
      value: "{{ dns_record_value }}"
      ttl: "{{ dns_ttl_default }}"
- name: Append zone DMARC record variable
  ansible.builtin.set_fact:
    dns_zones: "{{ dns_zones | combine({dns_zone: {'TXT': [dns_zone_data]}}, recursive=true, list_merge='append') }}"
  vars:
    dns_zone_data:
      name: _dmarc.{{ dns_zone }}.
      ttl: "{{ dns_ttl_default }}"
      type: TXT
      value: "{{ dns_record_value }}"
      comment: DMARC Record
