---
- name: Set recode variables
  ansible.builtin.set_fact:
    dns_recode:
      name: "{{ dns_domain | community.dns.remove_registrable_domain | default('@', true) }}"
      type: A
      value: "{{ lookup('ansible.builtin.template', 'recode/AAAA.j2') | trim }}"
- name: Combine AAAA recode
  ansible.builtin.set_fact:
    dns_domain_recodes: "{{ dns_domain_recodes | combine({'AAAA': dns_recode}, recursive=true) }}"
