---
- name: Initialize zone AAAA recode variable
  ansible.builtin.set_fact:
    dns_zones: "{{ dns_zones | combine({dns_zone: {'AAAA': []}}, recursive=true) }}"
  when: dns_zones[dns_zone]['AAAA'] is undefined
- name: Set recode value variables
  ansible.builtin.set_fact:
    dns_recode_value: "{{ lookup('ansible.builtin.template', 'recode/AAAA.j2') | trim }}"
- name: Combine AAAA recode
  ansible.builtin.set_fact:
    dns_domain_recodes: "{{ dns_domain_recodes | combine({'AAAA': dns_recode}, recursive=true) }}"
  vars:
    dns_recode:
      name: "{{ dns_recode_name }}"
      type: AAAA
      value: "{{ dns_recode_value }}"
