---
- name: Set recode variables
  ansible.builtin.set_fact:
    dns_recode:
      name: "{{ dns_domain | community.dns.remove_registrable_domain | default('@', true) }}"
      type: CNAME
      value: "{{ dns_domain_setting.cname }}"
- name: Combine CNAME recode value
  ansible.builtin.set_fact:
    dns_domain_recodes: "{{ dns_domain_recodes | combine({'CNAME': dns_recode}, recursive=true) }}"
