---
- name: Set DKIM recode Data
  when: dns_dkim_key_table_data[dns_domain] is defined
  block:
    - name: Read public key content
      ansible.builtin.command:
        cmd: cat {{ dns_dkim_key_table_data[dns_domain][1] }}
        removes: "{{ dns_dkim_key_table_data[dns_domain][1] }}"
      register: cat_result
      changed_when: false
    - name: Generate DNS DKIM recode
      when: cat_result.stdout is defined
      block:
        - name: Extraction DNS recode value
          ansible.builtin.set_fact:
            dns_dkim_reocode_value: "{{ cat_result.stdout.split('(')[1].split(')')[0] }}"
        - name: Transform DNS recode value(replace whitespace)
          ansible.builtin.set_fact:
            dns_dkim_reocode_value: "{{ dns_dkim_reocode_value | trim | regex_replace('\"\\s+\"', '') }}"
        - name: Transform DNS recode value(Trim doble quote)
          ansible.builtin.set_fact:
            dns_dkim_reocode_value: "{{ dns_dkim_reocode_value | regex_replace('^\"', '') | regex_replace('\"$', '') }}"
        - name: Set recode variables
          ansible.builtin.set_fact:
            dns_recode:
              name: "{{ dns_dkim_key_table_data[dns_domain][0] | default('@', true) }}"
              type: TXT
              value: "{{ dns_dkim_reocode_value }}"
        - name: Combine DKIM recode
          ansible.builtin.set_fact:
            dns_domain_recodes: "{{ dns_domain_recodes | combine({'DKIM': dns_recode}, recursive=true) }}"
