---
- name: Gather IP Address
  ansible.builtin.setup:
    gather_subset:
      - default_ipv4
      - default_ipv6
- name: Set recode value
  ansible.builtin.set_fact:
    spf_recode: "{{ lookup('ansible.builtin.template', 'spf.j2') | replace('\n', ' ') }}"
- name: Combine SPF recode value
  ansible.builtin.set_fact:
    dns_recode: "{{ dns_recode | combine({'SPF': spf_recode}) }}"
