---
- name: Set recode variables
  ansible.builtin.set_fact:
    dns_recode:
      name: "{{ opendkim_sector | default('*') }}._domainkey.{{ dns_dkim_domain }}"
      type: TXT
      rdata: "{{ lookup('ansible.builtin.template', 'DKIM.j2') | trim | replace('\n', '; ') }}"
- name: Combine SPF recode value
  ansible.builtin.set_fact:
    dns_recodes: "{{ dns_recodes | combine({'DKIM': dns_recode}) }}"
