---
- name: Set recode variables
  ansible.builtin.set_fact:
    dns_recode:
      name: _dmarc
      type: TXT
      value: "{{ lookup('ansible.builtin.template', 'recode/DMARC.j2') | trim | replace('\n', '; ') }};"
- name: Combine DMARC recode
  ansible.builtin.set_fact:
    dns_domain_recodes: "{{ dns_domain_recodes | combine({'DMARC': dns_recode}, recursive=true) }}"
