---
- name: Set recode variables
  ansible.builtin.set_fact:
    dns_recode:
      name: _dmarc
      type: TXT
      rdata: "{{ lookup('ansible.builtin.template', 'DMARC.j2') | trim | replace('\n', '; ') }};"
- name: Combine SPF recode value
  ansible.builtin.set_fact:
    dns_recodes: "{{ dns_recodes | combine({'DMARC': dns_recode}) }}"
