---
- name: Set recode variables
  ansible.builtin.set_fact:
    dns_recode:
      name: "{{ dns_domain | community.dns.remove_registrable_domain }}"
      type: TXT
      rdata: "{{ dns_domain_setting.postmaster }};"
- name: Combine DMARC recode value
  ansible.builtin.set_fact:
    dns_domain_recodes: "{{ dns_domain_recodes | combine({'Postmaster Tools': dns_recode}, recursive=true) }}"
