---
- name: Check variable
  when: dns_rtp_domain
  block:
    - name: Split IP Address variables
      ansible.builtin.set_fact:
        dns_ptr_parts: "{{ ansible_facts.default_ipv4.address | split('.') }}"
    - name: Set recode variables
      ansible.builtin.set_fact:
        dns_recode:
          name: "{{ dns_ptr_parts[3] }}.{{ dns_ptr_parts[2] }}.{{ dns_ptr_parts[1] }}.{{ dns_ptr_parts[0] }}.in-addr.arpa"
          type: PTR
          rdata: "{{ dns_rtp_domain }}"
    - name: Combine SPF recode value
      ansible.builtin.set_fact:
        dns_recodes: "{{ dns_recodes | combine({'PTR': dns_recode}) }}"
