---
- name: Initialize zone TXT recode variable
  ansible.builtin.set_fact:
    dns_zones: "{{ dns_zones | combine({dns_zone: {'TXT': []}}, recursive=true) }}"
  when: dns_zones[dns_zone]['TXT'] is undefined
- name: Set recode variables
  ansible.builtin.set_fact:
    dns_recode:
      name: "{{ dns_domain | community.dns.remove_registrable_domain | default('@', true) }}"
      type: TXT
      value: "{{ dns_domain_setting.site_verification }};"
- name: Combine Site verification recode
  ansible.builtin.set_fact:
    dns_domain_recodes: "{{ dns_domain_recodes | combine({'Site verification': dns_recode}, recursive=true) }}"
