---
- name: Set recode variables
  ansible.builtin.set_fact:
    dns_recode:
      name: "{{ dns_domain | community.dns.remove_registrable_domain | default('@', true) }}"
      type: TXT
      rdata: "{{ dns_domain_setting.site_verification }};"
- name: Combine Site verification recode
  ansible.builtin.set_fact:
    dns_domain_recodes: "{{ dns_domain_recodes | combine({'Site verification': dns_recode}, recursive=true) }}"
