---
- name: Set recode variables
  ansible.builtin.set_fact:
    dns_recode:
      name: "{{ dns_spf.name | default('@') }}"
      type: TXT
      rdata: "{{ lookup('ansible.builtin.template', 'SPF.j2') | trim | replace('\n', ' ') }}"
- name: Combine SPF recode value
  ansible.builtin.set_fact:
    dns_recodes: "{{ dns_recodes | combine({'SPF': dns_recode}) }}"
