---
- name: Set recode variables
  ansible.builtin.set_fact:
    dns_recode:
      name: "{{ dns_domain | community.dns.remove_registrable_domain | default('@', true) }}"
      type: TXT
      rdata: "{{ lookup('ansible.builtin.template', 'SPF.j2') | trim | replace('\n', ' ') }}"
- name: Combine SPF recode value
  ansible.builtin.set_fact:
    dns_domain_recodes: "{{ dns_domain_recodes | combine({'SPF': dns_recode}, recursive=true) }}"
