# code: language=ansible
---
- name: Converge
  hosts: all
  gather_facts: true
  become: true
  vars:
    opendkim_rsa_keylen: 1024
  pre_tasks:
    - name: Update cache(apt)
      ansible.builtin.apt:
        update_cache: true
      when: ansible_facts.pkg_mgr == 'apt'
    - name: Update cache(dnf)
      ansible.builtin.dnf:
        update_cache: true
      when: ansible_facts.pkg_mgr == 'dnf'
  roles:
    - role: opendkim
  tasks:
    - name: Include role
      ansible.builtin.include_role:
        name: "{{ lookup('env', 'MOLECULE_PROJECT_DIRECTORY') | basename }}"
