# code: language=ansible
---
# - name: Set Install version variable
#   when: dns_version == 'latest'
#   block:
#     - name: Get latest release
#       ansible.builtin.uri:
#         url: https://api.github.com/repos/{{ dns_repo_owner }}/{{ dns_repo_name }}/releases/latest
#         headers:
#           Accept: application/vnd.github+json
#       register: latest_releases
#     - name: Set package version variable
#       ansible.builtin.set_fact:
#         dns_version: "{{ latest_releases.json.tag_name }}"
# - name: Set pckage file variable
#   ansible.builtin.set_fact:
#     package_file: dns_{{ dns_version[1:] }}_{{ architecture_files[ansible_facts['architecture']] }}.deb
#   vars:
#     architecture_files:
#       x86_64: amd64
#       aarch64: arm64
# - name: Install dns
#   ansible.builtin.apt:
#     deb: https://github.com/{{ dns_repo_owner }}/{{ dns_repo_name }}/releases/download/{{ dns_version }}/{{ package_file }}
- name: Install dns packages
  ansible.builtin.apt:
    name: "{{ dns_packages }}"
